name: Publish Nextcloud to DockerHub
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set ENV
        run: |
          echo "RELEASE_VERSION_ALL=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
          echo "RELEASE_VERSION_SUB=$(echo ${GITHUB_REF:10:1})" >> $GITHUB_ENV
          echo "RELEASE_VERSION_MAIN=$(echo ${GITHUB_REF:10:3})" >> $GITHUB_ENV
          echo "${{ env.RELEASE_VERSION_ALL }}"
          echo "${{ env.RELEASE_VERSION_SUB }}"
          echo "${{ env.RELEASE_VERSION_MAIN }}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: halfcoke/nextcloud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION_ALL }},${{ env.RELEASE_VERSION_SUB }},${{ env.RELEASE_VERSION_MAIN }}"
          dockerfile: docker/nextcloud/Dockerfile